name: Java Push Demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installing Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          
      - name: Check Java Version
        run: java --version

      - name: Compile Java
        run: javac HelloWorld.java

      - name: Run Java Application
        run: java HelloWorld

      
